#!/bin/sh


SCRIPT_PATH="${BASH_SOURCE:-$0}"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

WORKSTATION_DIR=$(fasd -d workstations)

echo "Copying files to $WORKSTATION_DIR/home/zgagnon"

rsync -av --exclude=".git" "$SCRIPT_DIR/" "$WORKSTATION_DIR/home/zgagnon"

(
  cd "$WORKSTATION_DIR/home/zgagnon" || exit
  ls -a
  git add .
  git st
  read -p "Press any key to continue..." -n1 -s
  git ci
)
