#+title: Machine Configuration and Dotfile Management
#+author: Zoe Gagnon
#+date:  2024-02-27

*

* Flake.nix
:PROPERTIES:
:header-args: :tangle flake.nix :comments org
:END:


The flake.nix is the over-arching control point for the configuration. It is responsible for gathering the various package sources and applying the correct configuration for each machine.

#+begin_src nix
  {
    description = "Machine Configuration Flake";
#+end_src

These inputs provide the channels the flake will consume
#+begin_src nix
    inputs = {
      nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
      home-manager.url = "github:nix-community/home-manager/release-23.11";
      darwin.url = "github:lnl7/nix-darwin";
      darwin.inputs.nixpkgs.follows = "nixpkgs";
    };
#+end_src


#+begin_src nix
    outputs = { self, nixpkgs, home-manager, darwin, ... }: {
#+end_src


Configuration for the Mechanical Orchard work Macbook [[file:hosts/Zells-MacBook-Pro/default.org]]
#+begin_src nix
     darwinConfigurations."Zells-MacBook-Pro" = darwin.lib.darwinSystem {
      system = "aarch64-darwin";
      modules = [
        home-manager.darwinModules.home-manager
        ./hosts/Zells-MacBook-Pro/default.nix
       ];
     };
    };
#+end_src
#+begin_src nix
  }
#+end_src

* Switch Script
:PROPERTIES:
 :header-args: :tangle switch :shebang :comments org
 :END:

A quick script to speed up switching to a new darwin generation on some Mac machines

Kandji (a tool used by MO) likes to edit this and break nix control. I don't care about the kandji thing,
so just delete it before we start.
#+begin_src nix
rm ~/.ssh/config
#+end_src

Switch to the new generation.

#+begin_src nix
darwin-rebuild switch --flake ~/darwin-flake/ --fallback
#+end_src

After the update, we need to source our .zshrc in this session, so place the source line in the paste buffer

#+begin_src nix
echo "source ~/.zshrc" | pbcopy
#+end_src

* DOOM Emacs

All emacs config is located in [[file:doom/config.org]]
