#!/usr/bin/env bash

# if we want to grab, then git pr and set mob timer to 10 minutes
if [ "$1" == "grab" ]; then
  git pr
  (sleep 30 && say "timer pop") &
  #mob timer 10
  exit
fi

# if we want to share, then git commit with a with and push
if [ "$1" == "share" ]; then
  git ci -am "WIP: $2"
  git push
  exit
fi
