{ pkgs, extraPackages,... }:
let
gdk = pkgs.google-cloud-sdk.withExtraComponents (with pkgs.google-cloud-sdk.components; [
    gke-gcloud-auth-plugin
  ]);
in
with pkgs;
[
  # extraPackages.lexical
  _1password-cli
  action-validator
  aider-chat
  anki-bin
  bat
  cabal-install
  cachix
  coreutils
  csharpier
  direnv
  elixir_1_17
  emacs30
  emacs-lsp-booster
  erlfmt
  eza
  fasd
  fd
  figlet
  fira-code
  gh
  gnugrep
  gdk
  haskellPackages.hoogle
  haskellPackages.lsp
  jetbrains.idea-community
  just
  kubectx
  kubernetes-helm
  mods
  nil
  nixfmt-rfc-style
  nodePackages.js-beautify
  nodePackages.typescript-language-server
  nodejs
  pandoc
  pgadmin4-desktopmode
  ripgrep
  shellcheck
  shfmt
  stgit
  stylelint
  terraform
  thefuck
  tree-sitter
  tree-sitter-grammars.tree-sitter-heex
  vscodium
  zellij
]
